name: Deploy Static Website to EC2

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Copy Files to EC2
    uses: appleboy/scp-action@v0.1.7
    with:
      host: ${{ secrets.SSSH_SECRET }}
      username: ubuntu
      key: ${{ secrets.SSSH_SECRET }}
      source: "./*"
      target: "/tmp/todo-app"

  - name: Move Files to Web Directory
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.SSSH_SECRET }}
      username: ubuntu
      key: ${{ secrets.SSH_KEY }}
      script: |
        sudo mkdir -p /var/www/todo-app
        sudo cp -r /tmp/todo-app/* /var/www/todo-app/
        sudo chown -R www-data:www-data /var/www/todo-app
        sudo chmod -R 755 /var/www/todo-app
        sudo systemctl restart nginx
